version: "3.9"

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-app
    restart: always
    ports:
      - "8080:8080"
    networks:
      - vue-network
    env_file:
      - .env
networks:
  vue-network:
    driver: bridge